# Site settings
title:          Econ Research Reproduced
description:    "A site dedicated to re-exploring older papers in economics"
url:            "https://edgongithub.github.io/"

# Author
author:
  name:         Ed Jee
  url:          https://edgongithub.github.io/
  email:        e.m.jee@lse.ac.uk

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
