# Site settings
title:          Ed's Website
description:    "A collection of econ blogposts"
url:            "https://edjeeongithub.github.io/"

# Author
author:
  name:         Ed Jee
  url:          https://edjeeongithub.github.io/
  email:        edjee@uchicago.edu

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

exclude: ['*.Rmd', 'title_template.txt']
