---
output: 
  html_document:
    code_folding: show
    highlight: kate
    theme: paper
editor_options:
  chunk_output_type: console
---

I do XYZ.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
library(dplyr)
MRW_clean <- readr::read_csv('assets/Transformed Data/MRW_clean_new_dummies.csv') %>% 
  mutate(n_g_d = (working_age_pop_ch + 5)/ 100,
         s = s / 100)
library(broom)
collect.results <- function(models, names){
  
  results <- map2_dfr(.x = models,
                      .y = names,
                      .f = function(x, y){tidy(x) %>% mutate(subset = y)}) %>% 
    as_tibble()
  return(results)
}


plot_new_vs_old <- function(term_type, data, std_error = FALSE ){
  if (std_error == TRUE){
    data <- data %>% 
      mutate(estimate = `std.error`)
  }
  
  new_data <- data %>% 
    filter(term == term_type) %>% 
    filter(type == 'New') %>% 
    mutate(estimate = abs(estimate))
  
  old_data <- data %>% 
    filter(term == term_type) %>% 
    filter(type == 'Original') %>% 
    mutate(estimate =  abs(estimate))
  
  
  p <- plot_ly(new_data,
               x = ~subset,
               y = ~estimate,
               type = 'bar',
               color = ~subset)
  
  q <- plot_ly(old_data,
               x = ~subset,
               y = ~estimate,
               type = 'bar',
               color = ~subset,
               colors = "Set1")
  
  pq <- subplot(p, q, nrows = 1, shareY = TRUE, shareX = TRUE) %>% 
    layout(yaxis = list(title = term_type))
  return(pq)
}
```


Running the restricted regressions.
```{r, table_1}
library(purrr)
library(tidyr)

MRW_clean_restricted <- MRW_clean %>% 
  mutate(restricted_regressor = log(s) - log(n_g_d))
restricted_models_old <- c('N',
                      'I',
                      'O') %>% 
  map(sym) %>% 
  map(~filter(MRW_clean_restricted, !!. == 1)) %>% 
  map(~lm(log(`1985`) ~ restricted_regressor,
                       data = .)) 



```


Collecting results and calculating alpha. Then do same for augmented model.
```{r}
  

restricted_model_results_old <- restricted_models_old %>% 
  collect.results(., names = c("OECD Restricted Classic",
                               "Intermediate Restricted Classic",
                               "Non-Oil Restricted Classic"))

calculate.alpha <- function(estimate){
  alpha <- estimate / (1 + estimate)
  return(alpha)
}
restricted_model_results_old <- restricted_model_results_old %>% 
  mutate(alpha = ifelse((term == 'restricted_regressor'), calculate.alpha(estimate), NA))

## Augmented model
MRW_augmented_restricted <- MRW_clean_restricted %>% 
  mutate(restricted_regressor_hc = log(school / 100) - log(n_g_d))

augmented_restricted_model_old <- c("O",
                                "I",
                                "N") %>% 
  map(sym) %>% 
  map(~filter(MRW_augmented_restricted, !!. == 1)) %>% 
  map(~lm(log(`1985`) ~ restricted_regressor + restricted_regressor_hc,
          data = .)) %>% 
  collect.results(., names = c("OECD Restricted Augmented",
                               "Intermediate Restricted Augmented",
                               "Non-Oil Restricted Augmented"))


find.param <- function(y, x){
  param <- (x*y) / (x + x^2 + x*y)
  return(param)
}

augmented_parameters <- augmented_restricted_model_old %>%
  select(term, subset, estimate) %>% 
  filter(term != "(Intercept)") %>% 
  spread(term, estimate) %>% 
  mutate(alpha = find.param(restricted_regressor_hc, restricted_regressor),
         beta = find.param(restricted_regressor, restricted_regressor_hc),
         alpha = round(alpha, 2),
         beta = round(beta, 2)) %>% 
  select(subset, alpha, beta)

classic_parameters <- restricted_model_results_old %>% 
  select(subset, alpha) %>% 
  drop_na() %>% 
  mutate(alpha = round(alpha, 2))

classic_parameters
augmented_parameters

estimated_parameters_old <- bind_rows(classic_parameters,
                                  augmented_parameters) %>% 
  separate(subset, c("subset",
                     "estimation_type",
                     "model_type"),
           sep = " ")
estimated_parameters_old
```



now comparing with new subset estimates

```{r}


classic_parameters_new <- c("oil",
                           "developing_no_oil",
                           "intermediate_no_oil",
                           "rich") %>%  
  map(~filter(MRW_clean_restricted, club == .)) %>% 
  map(~lm(log(`1985`) ~ restricted_regressor,
                       data = .)) %>% 
  collect.results(., names = c("Oil Restricted Classic",
                               "Developing Restricted Classic",
                               "Intermediate Restricted Classic",
                               "Rich Restricted Classic")) %>% 
  mutate(alpha = ifelse((term == 'restricted_regressor'), calculate.alpha(estimate), NA))




augmented_parameters_new <- c("oil",
                           "developing_no_oil",
                           "intermediate_no_oil",
                           "rich") %>% 
  map(~filter(MRW_augmented_restricted, club == .)) %>% 
  map(~lm(log(`1985`) ~ restricted_regressor + restricted_regressor_hc,
                       data = .)) %>% 
  collect.results(., names = c("Oil Restricted Augmented",
                               "Developing Restricted Augmented",
                               "Intermediate Restricted Augmented",
                               "Rich Restricted Augmented")) %>% 
  select(term, subset, estimate) %>% 
  filter(term != "(Intercept)") %>% 
  spread(term, estimate) %>% 
  mutate(alpha = find.param(restricted_regressor_hc, restricted_regressor),
         beta = find.param(restricted_regressor, restricted_regressor_hc),
         alpha = round(alpha, 2),
         beta = round(beta, 2)) %>% 
  select(subset, alpha, beta)



###
classic_parameters_new <- classic_parameters_new %>% 
  select(subset, alpha) %>% 
  drop_na() %>% 
  mutate(alpha = round(alpha, 2))

classic_parameters_new
augmented_parameters_new

estimated_parameters_new <- bind_rows(classic_parameters_new,
                                  augmented_parameters_new) %>% 
  separate(subset, c("subset",
                     "estimation_type",
                     "model_type"),
           sep = " ")
estimated_parameters_new

```



dropping oil as a little crazy and comparing

```{r}
library(knitr)
estimated_parameters_new_no_oil <- estimated_parameters_new %>% 
  filter(subset != 'Oil')


comparison_tbl <- bind_rows(estimated_parameters_new_no_oil %>%
                              select(model_type, subset, alpha, beta) %>%
                              mutate(type = 'New'),
                            estimated_parameters_old %>% select(model_type, subset, alpha, beta) %>% 
                              mutate(subset = paste0(subset, ' MRW'),
                                     type = 'Original')) 

comparison_tbl %>%
  head %>% 
  kable
```


plotting alpha and beta

```{r}
library(plotly)
library(forcats)
comparison_plot <- comparison_tbl %>% 
  gather(term, estimate, alpha, beta)

comparison_plot$subset <- factor(comparison_plot$subset,
                                 levels = c('Developing',
                                            'Intermediate',
                                            'Rich',
                                            'Non-Oil MRW',
                                            'Intermediate MRW',
                                            'OECD MRW'),
                                 ordered = TRUE)


p <- plot_new_vs_old('alpha', comparison_plot)

q <- plot_new_vs_old('beta', comparison_plot) 


subplot(p, q, nrows = 2, titleY = TRUE) %>% 
  layout(showlegend = FALSE,
         title = 'Calculating alpha and beta with new and old partitions')


```



```{r, modelling}
k <- rep(seq(from = 0, to = 50, by = .5), nrow(MRW_clean))
countries <- rep(MRW_clean$country, 50/0.5 + 1)

country_tbl <- tibble('k' = k,
                      'country' = countries) %>% 
  left_join(y = MRW_clean %>% 
              select(s, n_g_d, country, club), by = 'country')


estimated_parameters_new$club <- estimated_parameters_new$subset %>% 
  gsub('Oil', 'oil', .) %>% 
  gsub('Developing', 'developing_no_oil', .) %>% 
  gsub('Intermediate', 'intermediate_no_oil', .) %>% 
  gsub('Rich', 'rich', .)

country_tbl <- left_join(country_tbl, estimated_parameters_new %>% 
                           select(club, model_type, alpha, beta),
                         by = 'club')


find.saving.point <- function(k, alpha, s){
  point <- s*k^alpha
  return(point)
}

find.effective.depreciation <- function(k, n = 0, g = 0, d = 0){
  eff_depreciation <- k*(n + g + d)
  return(eff_depreciation)
}

country_tbl <- country_tbl %>% 
  mutate(savings_curve = find.saving.point(k = k,
                                           alpha = alpha,
                                           s = s),
         depreciation_curve = find.effective.depreciation(k = k,
                                                          n = n_g_d))
random_country <- sample(country_tbl$country, size = 1)
ggplot(country_tbl %>% 
         filter(model_type == "Classic") %>% 
         filter(country == random_country), aes(k, savings_curve, group = country)) +
  geom_line() +
  ggtitle(random_country)



ggplot(country_tbl %>% 
         filter(model_type == "Classic") %>% 
         filter(club != "oil"),
       aes(k, savings_curve, group = country,
           colour = club)) +
  geom_line(size = 1) +
  theme_minimal()

plot_dat <- country_tbl %>% 
         filter(model_type == "Classic") %>% 
         filter(club != "oil")

plot_ly(plot_dat %>% 
          group_by(country) %>% 
          filter(country == 'United Kingdom'),
        x = ~k,
        y = ~savings_curve,
        color = ~club,
        text = ~country) %>% 
  add_lines() %>% 
  add_lines(y = ~depreciation_curve)


plot_ly(plot_dat %>% 
          group_by(country),
        x = ~k,
        y = ~depreciation_curve,
        color = ~club,
        text = ~country) %>% 
  add_lines()

ggplot(plot_tbl,
       aes(x = k,
           y = s)) +
  geom_point() +
  geom_point(aes(k, n_g_d)) +
  geom_point(aes(k_star$s, find.saving.point(k_star,
                                           alpha_uk,
                                           s_uk)$s),
             colour = 'red')






library(plotly)




uk_k_t <- tibble(time = seq(from = 0, to = 100, by = 1))
init_k <- 0

k_star <- (s_uk / n_g_d_uk) ^ (1 / (1 - alpha_uk))

k <- calculate.k.t.1(k = 1,
           s = s_uk,
           n = n_g_d_uk,
           g = 0,
           d = 0,
           alpha = alpha_uk)
init_matrix <- matrix(nrow = 100, ncol = 4)
init_matrix[1:100, 1] <- c(seq(from = 1, to = 100, by = 1))
for (i in 1:100){
  k <- calculate.k.t.1(k = k[[3]],
           s = s_uk,
           n = n_g_d_uk,
           g = 0,
           d = 0,
           alpha = alpha_uk)
  init_matrix[i, 2:4] <- k %>% unlist()


}

k_tbl <- init_matrix %>% as_tibble()
colnames(k_tbl) <- c("time",
                     "savings",
                     "effective_depreciation",
                     "k_t_1")
k_tbl <- k_tbl %>% 
  mutate(k_t = lag(k_t_1))
library(ggplot2)
ggplot(k_tbl,
       aes(k_t, k_t_1)) +
  geom_point() +
  geom_point(aes(k_t, savings))


```


```{r, stargazer, results='asis'}
library(latex2exp)
restricted_models %>% 
    stargazer::stargazer(type = 'html',
                       column.labels = c("Non-Oil",
                                         "Intermediate",
                                         "OECD"),
                       digits = 2,
                       omit.stat = "f",
                       df = FALSE,
                       covariate.labels = c("ln(I/Y) - ln(n + g + d)",
                                            "CONSTANT"),
                       add.lines = list(c("Implied alpha", classic_parameters$alpha)))
```

